# Generated by Django 3.0.6 on 2020-06-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Username')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái kích hoạt')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Nhân viên')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Nhân viên quản lý')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Quản lý cao cấp')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày thêm')),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Lần đăng nhập cuối')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': 'Khách Hàng',
                'verbose_name_plural': 'Danh Sách Khách Hàng',
                'managed': True,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.account',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'verbose_name': 'Nhân Viên',
                'verbose_name_plural': 'Danh Sách Nhân viên',
                'managed': True,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.account',),
        ),
    ]
