# Generated by Django 3.0.6 on 2020-06-25 17:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255, verbose_name='Tên Thiết bị')),
                ('device_id', models.CharField(max_length=10, unique=True, verbose_name='Mã Thiết bị')),
                ('device_type', models.CharField(max_length=127, verbose_name='Loại Thiết Bị')),
                ('is_active', models.BooleanField(default=False, verbose_name='Trạng thái')),
                ('turn_on_cond', models.FloatField(verbose_name='Điều kiện khởi động')),
                ('turn_off_cond', models.FloatField(verbose_name='Điều kiện tắt')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255, verbose_name='tên cảm biến')),
                ('sensor_id', models.CharField(max_length=10, unique=True, verbose_name='Mã Cảm biến')),
                ('sensor_type', models.CharField(max_length=127, verbose_name='Loại cảm biến')),
                ('location', models.CharField(max_length=127, verbose_name='Vị trí')),
                ('is_active', models.BooleanField(default=False, verbose_name='Trạng thái')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agri.Device', verbose_name='thiết bị liên kết')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', django.contrib.postgres.fields.jsonb.JSONField(editable=False, verbose_name='thông số')),
                ('on_created', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian report')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agri.Sensor', verbose_name='Cảm biến report')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nông trại')),
                ('farm_map', models.TextField(verbose_name='Bản đồ trang trại')),
                ('location', models.CharField(max_length=127, verbose_name='Vị trí trang trại')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agri.Device')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agri.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bắt đầu')),
                ('time_finish', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('status', models.IntegerField(choices=[(1, 'Khởi tạo'), (2, 'Đang thực thi'), (3, 'Đã hoàn thành')], verbose_name='Trạng thái')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agri.Device', to_field='device_id', verbose_name='Thiết bị điều khiển')),
                ('report_after', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_after', to='agri.Report', verbose_name='thông số sau điều khiển')),
                ('report_before', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_before', to='agri.Report', verbose_name='thông số trước điều khiển')),
            ],
        ),
    ]
