# Generated by Django 3.0.6 on 2020-06-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='index',
            field=models.TextField(editable=False, verbose_name='thông số'),
        ),
    ]
