# Generated by Django 3.0.6 on 2020-07-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0003_auto_20200705_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='time_finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc'),
        ),
    ]
